---
- name: Delete host from Ansible Tower inventory
  hosts: localhost
  vars:
    credfile: "../../.mycreds/democreds.yml"
    vm_fq_hostname: "ERROR-NEED-TO-SPECIFY-HOST"
    tower_inventory: "ERROR-NEED-TO-SPECIFY-INVENTORY"
    tower_hostname: "tower.example.com"

  tasks:

    - name: Check for credentials file
      stat:
        path: "{{ credfile }}"
      register: stat_results

    - name: Define credentials using local file
      block:

      - name: Include variable definitions from local file
        include_vars:
          file: "{{ credfile }}"

      - name: Define Ansible Tower credentials based on local file
        set_fact:
          at_rest_user: "{{ cf_tower_username }}"
          at_rest_password: "{{ cf_tower_password }}"

      when: stat_results.stat.exists

    - name: Define credentials using Ansible Tower custom credentials
      block:

      - name: Define Ansible Tower credentials based on custom credential
        set_fact:
          at_rest_user: "{{ at_tower_username }}"
          at_rest_password: "{{ at_tower_password }}"

      when: not stat_results.stat.exists

    - name: Print host to delete
      debug:
        msg: "Deleting host {{ vm_fq_hostname }}"

    - name: Delete host from inventory
      tower_host:
        inventory: "{{ tower_inventory }}"
        name: "{{ vm_fq_hostname }}"
        state: absent
        tower_host: "{{ tower_hostname }}"
        tower_password: "{{ at_rest_password }}"
        tower_username: "{{ at_rest_user }}"
        tower_verify_ssl: No
