---
- name: Add host to Ansible Tower inventory
  hosts: localhost
  vars:
    credfile: "../../.mycreds/democreds.yml"
    vm_fq_hostname: "ERROR-NEED-TO-SPECIFY-HOST"
    tower_inventory: "ERROR-NEED-TO-SPECIFY-INVENTORY"
    tower_group: ""
    host_defined: ""
    tower_base_url: "https://tower.example.com/api/v2/"

  tasks:

    - name: Check for credentials file
      stat:
        path: "{{ credfile }}"
      register: stat_results

    - name: Define credentials using local file
      block:

      - name: Include variable definitions from local file
        include_vars:
          file: "{{ credfile }}"

      - name: Define Ansible Tower credentials based on local file
        set_fact:
          at_rest_user: "{{ cf_tower_username }}"
          at_rest_password: "{{ cf_tower_password }}"

      when: stat_results.stat.exists

    - name: Define credentials using Ansible Tower custom credentials
      block:

      - name: Define Ansible Tower credentials based on custom credential
        set_fact:
          at_rest_user: "{{ at_tower_username }}"
          at_rest_password: "{{ at_tower_password }}"

      when: not stat_results.stat.exists

    - name: Get list of inventories
      uri:
        url: "{{ tower_base_url }}inventories/"
        method: GET
        force_basic_auth: yes
        user: "{{ at_rest_user}}"
        password: "{{ at_rest_password }}"
        validate_certs: No
        status_code:
          - 200
      register: inventory_list

    - name: Set the inventory ID
      set_fact:
        inventory_id: "{{ item.id }}"
      with_items: "{{ inventory_list.json.results }}"
      when: item.name == "{{ tower_inventory }}"

    - name: Build host query URL
      set_fact:
        host_query_url: "{{ tower_base_url }}inventories/{{ inventory_id }}/hosts/"

    - name: Get list of all hosts in inventory
      uri:
        url: "{{ host_query_url }}"
        method: GET
        force_basic_auth: yes
        user: "{{ at_rest_user}}"
        password: "{{ at_rest_password }}"
        validate_certs: No
        status_code:
          - 200
      register: host_list

    - name: Set variable if host is defined
      set_fact:
        host_defined: True
      with_items: "{{ host_list.json.results }}"
      when: item.name == "{{ vm_fq_hostname }}"

    - name: Fail play if host is already defined
      fail:
        msg: "Host {{ vm_fq_hostname }} is already defined in inventory"
      when: host_defined|bool

    - name: Add host to the specified group in the inventory
      block:

      - name: Build group query URL
        set_fact:
          group_query_url: "{{ tower_base_url }}inventories/{{ inventory_id }}/groups/"

      - name: Get list of groups for the inventory
        uri:
          url: "{{ group_query_url }}"
          method: GET
          force_basic_auth: yes
          user: "{{ at_rest_user}}"
          password: "{{ at_rest_password }}"
          validate_certs: No
          status_code:
            - 200
        register: group_list

      - name: Set the group ID
        set_fact:
          group_id: "{{ item.id }}"
        with_items: "{{ group_list.json.results }}"
        when: item.name == "{{ tower_group }}"

      - name: Build add-host-to-group URL
        set_fact:
          add_host_to_group_url: "{{ tower_base_url }}groups/{{ group_id }}/hosts/"

      - name: Add host to group in inventory
        uri:
          url: "{{ add_host_to_group_url }}"
          method: POST
          force_basic_auth: yes
          user: "{{ at_rest_user}}"
          password: "{{ at_rest_password }}"
          validate_certs: No
          body_format: json
          body:
            name: "{{ vm_fq_hostname }}"
            description: ""
            enabled: true
            instance_id: ""
            variables: ""
          status_code:
            - 200
            - 201
            - 202
        register: add_to_inventory_status

      when: tower_group|length > 0

    - name: Add host to the inventory - no group defined
      block:

      - name: Build add-host-to-inventory URL
        set_fact:
          add_host_to_inventory_uri: "{{ tower_base_url }}inventories/{{ inventory_id }}/hosts/"

      - name: Add host to Ansible Tower
        uri:
          url: "{{ add_host_to_inventory_uri }}"
          method: POST
          force_basic_auth: yes
          user: "{{ at_rest_user}}"
          password: "{{ at_rest_password }}"
          validate_certs: No
          body_format: json
          body:
            name: "{{ vm_fq_hostname }}"
            description: ""
            enabled: true
            instance_id: ""
            variables: ""
          status_code:
            - 201
        register: add_to_inventory_status

      when: tower_group|length == 0
